### ISSUE TITLE
Unable to calculate FLOPs

### ISSUE THREAD

**Issue by GreenLawrencek** [burchim/AVEC#8]
I get an error when I calculate FLOPs.

++++++++++++++++++++++++++++CODE+++++++++++++++++++++++++++++
model = nnet.AudioEfficientConformerInterCTC(vocab_size=vocab_size, att_type=att_type, interctc_blocks=interctc_blocks)

print('Total params: %.2fM' % (sum(p.numel() for p in model.parameters())/1000000.0))

flops, params = get_model_complexity_info(model, (1, 1, 16000), as_strings=True, print_per_layer_stat=True)
print('Flops:  ' + flops)
print('Params: ' + params)

+++++++++++++++++++++++++++++ERROR++++++++++++++++++++++++++++
(se) se@se-pc:/media/se/902C4B8E2C4B6E72/AVEC-master$ python main.py -c configs/LRS23/AO/EffConfCTC.py 
Mode: training
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    main(0, args)
  File "main.py", line 49, in main
    args.config = importlib.import_module(args.config_file.replace(".py", "").replace("/", "."))
  File "/home/se/anaconda3/envs/se/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/se/902C4B8E2C4B6E72/AVEC-master/configs/LRS23/AO/EffConfCTC.py", line 48, in <module>
    flops, params = get_model_complexity_info(model, (1, 1, 16000), as_strings=True, print_per_layer_stat=True)
  File "/home/se/anaconda3/envs/se/lib/python3.8/site-packages/ptflops/flops_counter.py", line 30, in get_model_complexity_info
    flops_count, params_count = get_flops_pytorch(model, input_res,
  File "/home/se/anaconda3/envs/se/lib/python3.8/site-packages/ptflops/pytorch_engine.py", line 44, in get_flops_pytorch
    _ = flops_model(batch)
  File "/home/se/anaconda3/envs/se/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/media/se/902C4B8E2C4B6E72/AVEC-master/nnet/models_zoo.py", line 57, in forward
    x, lengths = inputs
ValueError: not enough values to unpack (expected 2, got 1)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
How can I fix that ?  : )

**Comment by GreenLawrencek** [comment]
When I change the code to the following, I still get an error.
x, lengths = inputs[0], inputs[1]

(se) se@se-pc:/media/se/902C4B8E2C4B6E72/AVEC-master$ python main.py -c configs/LRS23/AO/EffConfCTC.py 
Mode: training
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    main(0, args)
  File "main.py", line 49, in main
    args.config = importlib.import_module(args.config_file.replace(".py", "").replace("/", "."))
  File "/home/se/anaconda3/envs/se/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/se/902C4B8E2C4B6E72/AVEC-master/configs/LRS23/AO/EffConfCTC.py", line 48, in <module>
    flops, params = get_model_complexity_info(model, (1, 1, 16000), as_strings=True, print_per_layer_stat=True)
  File "/home/se/anaconda3/envs/se/lib/python3.8/site-packages/ptflops/flops_counter.py", line 30, in get_model_complexity_info
    flops_count, params_count = get_flops_pytorch(model, input_res,
  File "/home/se/anaconda3/envs/se/lib/python3.8/site-packages/ptflops/pytorch_engine.py", line 44, in get_flops_pytorch
    _ = flops_model(batch)
  File "/home/se/anaconda3/envs/se/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/media/se/902C4B8E2C4B6E72/AVEC-master/nnet/models_zoo.py", line 57, in forward
    x, lengths = inputs[0], inputs[1]
IndexError: index 1 is out of bounds for dimension 0 with size 1

**Comment by burchim** [comment]
Hi,

The error happens because the model inputs should contain the audio signals of shape (batch, time) and the lengths of each audio signal in the batch to correctly mask the attention. The get_model_complexity_info function only provides the signal x as input.

In your case, you use a batch of one audio signal so you can add the following code [here](https://github.com/burchim/AVEC/blob/1bf8ad079b90af383090f1584a20fe9467f98f47/nnet/models_zoo.py#L72):
```
# x, lengths = inputs
x = inputs
lengths = torch.tensor([x.shape[-1]])
``` 
lengths is a tensor containing the lengths of audio signals in the batch.
I also think the correct resolution should be (16000,) for get_model_complexity_info  instead of (1, 1, 16000) since we are working with audio signals.

Best,
Maxime

**Comment by GreenLawrencek** [comment]
Thanks!
